### ISSUE TITLE
Relay 1 and 2 should initially be closed.

### ISSUE THREAD

**Issue by ArchitK1** [ArchitK1/wular#1]
Hello everyone,
This is my  Project in which i have used Relay and have some problems in it the problems stated as: 
Objective:   
There are 3 Relays in the project first and second relay will be open for first 3 seconds untill the condition is fulfilled.Then they go off and the third realy will get open for 2 seconds only at condition.

**Comment by 349aditya** [comment]
Refactor the code to separate concerns better. Have a clear function for LoRa packet handling, button press detection, and relay control.
Ensure proper initialization and reset of variables.
Comment your code to clarify the purpose of each section
